### ISSUE TITLE
Fix txpool ValidationOptionsWithState "ExistingCost" and "ExistingExpenditure"

### ISSUE THREAD

**Issue by hbandura** [celo-org/op-geth#110]
# Rationale

The validation options "ExistingCost" callback is used to check expenditure difference from previous and current tx from same nonce on a possible replacement. "ExistingExpenditure" on the other hand, is used to compute the total expenditure of all txs in the txpool for an account (and a specific currency).

Both of this functions (and its upstream interface) are not taking into account the fact that FeeCurrency transactions (both CeloDynamicFee and CeloDenominated) spend in two currencies at the same time: CELO (Value) and FeeCurrency (Fee). 

# Implementation

1. Modify 'list.go' to compute properly the totalcost on adding and removing txs (by modifying the totals for both currencies)
2. Modify the interface of the ValidationOptionsWithState be able to return both expenditures
3. Modify the code of ValidateTransactionWithState to use the new values and maintain the original intention of the logic.

**Comment by lvpeschke** [comment]
@karlb can you provide a status update? how much and what is left?

**Comment by karlb** [comment]
@lvpeschke The PR just needs a review.

**Comment by lvpeschke** [comment]
@karlb do you have an ETA for finishing the review?

**Comment by karlb** [comment]
@lvpeschke: I'm just back today and @ezdac reviewed the code in the mean time. I'll start addressing the review feedback today and I assume we can merge it tomorrow.
