### ISSUE TITLE
Document how to use RPC libraries to pay with alternative fee currencies

### ISSUE THREAD

**Issue by karlb** [celo-org/op-geth#140]
(This issue was created from a todo list item in https://github.com/celo-org/op-geth/issues/62. I don't have any specific tasks in mind, myself. Please update, comment or close as necessary.)

**Comment by karlb** [comment]
https://docs.celo.org/developer/fee-currency should be correct for both before and after the migration. Are there any changes needed, or can we just close this?

**Comment by aaronmgdr** [comment]
I believe https://github.com/celo-org/docs/issues/1325 covers what is needed

**Comment by karlb** [comment]
Great, let's close this as a duplicate, then.
