### ISSUE TITLE
Add types.Header marshaling using rlpgen

### ISSUE THREAD

**Issue by piersy** [celo-org/op-geth#145]
Previously rlpgen was used to generate faster rlp encoding methods for types.Header (Approx 40% faster). When updating to support data migrated from Celo we dropped the use of the generated code, but we should consider adding it back for the two header structures we support.

**Comment by palango** [comment]
@Kourin1996 this is fixed with https://github.com/celo-org/op-geth/pull/288, right?

**Comment by Kourin1996** [comment]
@palango I think so. This issue should be same with https://github.com/celo-org/celo-blockchain-planning/issues/720.
