### ISSUE TITLE
Configure CI for OP-geth

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/op-geth#2]
```[tasklist]
### Tasks
- [x] Set up CI for running tests
```

**Comment by karlb** [comment]
The current CirecleCI setup does not work without choosing a different CircleCI plan:
> Resource class docker for xlarge is not available for your project, or is not a valid resource class. This message will often appear if the pricing plan for this project does not support docker use.

**Comment by karlb** [comment]
@lvpeschke Let us know once there is an easy way to turn on support for xlarge docker instances on CircleCI for us.

**Comment by palango** [comment]
Resolved by https://github.com/celo-org/op-geth/pull/4
