### ISSUE TITLE
Correct branch to import types from

### ISSUE THREAD

**Issue by kamikazechaser** [celo-org/op-geth#249]
I want to start importing `go-ethereum` compatible types from this repo. However, it is unclear what the correct branch will be in the long-term. Is it safe to assume `celo8` is the active development branch from which tags will be created from?

**Comment by karlb** [comment]
We are treating our changes as a patch set on top op upstream op-geth. From time to time, we rebase our patch set on a more recent version of upstream. When that happens, we create a new `celo` branch with an increased number to avoid force pushes on the public branch and preserve the history.

The highest number celo branch is always the latest development branch. This is also the github default branch (which is the HEAD branch on the github remote if you want to deal with this in scripts).

Does this help?

**Comment by kamikazechaser** [comment]
> This is also the github default branch 

Thanks, I think that answers my question. `go get github.com/celo-org/op-geth` should always work.
