### ISSUE TITLE
Ensure that ReadOnlyStateDB methods are implemented, for all read usages of StateDB interface.

### ISSUE THREAD

**Issue by piersy** [celo-org/op-geth#57]
Currently the `core.ReadOnlyStateDB` only implements the read methods that were so far exercised, we should look at the code and ensure we implement every read method that is called on the `vm.StateDB` interface.

**Comment by palango** [comment]
Related to https://github.com/celo-org/celo-blockchain-planning/issues/355

**Comment by karlb** [comment]
Closed by https://github.com/celo-org/op-geth/pull/203
