### ISSUE TITLE
Port the block limit per fee currency feature

### ISSUE THREAD

**Issue by carterqw2** [celo-org/op-geth#65]
See https://github.com/celo-org/celo-blockchain/pull/2203

**Comment by lvpeschke** [comment]
End of weekly commitment check-in: @ezdac could you provide an update on progress?

**Comment by ezdac** [comment]
> End of weekly commitment check-in: @ezdac could you provide an update on progress?

@lvpeschke - This is awaiting review in #119 , and I don't expect this to require major changes to the proposed implementation.
