### ISSUE TITLE
Update gas limits for fee currency transfer calls and make problems inspectable

### ISSUE THREAD

**Issue by palango** [celo-org/op-geth#70]
Part of https://github.com/celo-org/optimism/issues/6

From https://github.com/celo-org/op-geth/pull/28/files/d42a08f6e2bd0fc7673c2a73e913810fa57dbad2#r1388691745
> Maybe should be just a TODO, but we could limit these numbers more. Technically Debit + Credit should be the same gas as the IntrinsicGasForAlternativeFeeCurrency, or at least the same order of magnitud.
Technically we could have an erc20 in the future that the transfer consumes more gas (a bug or the erc20 doing something nasty), and with that limit of 1M, we allow them to consume gas that we are not going to charge.
Probably reducing both to 50k is a valid option, but as I said, this could be part of another issue, but we could add it as a TODO

**Comment by karlb** [comment]
The result from https://www.notion.so/clabsco/Intrinsic-gas-for-CEL2-fee-currencies-919f3a76d1824fb9ac8f1031058d3f07?pvs=4#39972512102c42cc851332855d1db659 is

> How do we set maxGas when executing credit/debit?
> [snip]
> Result: 3 * intrinsic gas in total for debit+credit

So we should use `3 * intrinsic gas`.
