### ISSUE TITLE
Improve logging and add metrics

### ISSUE THREAD

**Issue by carterqw2** [celo-org/op-geth#74]
Metrics that would be nice to have:
- Txpool metrics for different transaction types and used fee currencies for EasyFee transactions
- Execution metrics for transaction types and fee currencies used

**Comment by karlb** [comment]
I think the metrics added in https://github.com/celo-org/op-geth/pull/199 are reasonable for now. We can add more metrics as we see a need for them. Feel free to reopen if you already see the need for a specific additional metric.
