### ISSUE TITLE
Add support for fetching gas prices for fee currencies

### ISSUE THREAD

**Issue by karlb** [celo-org/op-geth#79]
To choose good gas prices for CIP-64 txs, `eth_gasPrice` is called with a fee currency parameter. This is not yet supported.

The case can be triggered by removing `maxFeePerGas` from the [viem test case](https://github.com/celo-org/op-geth/blob/571f3689935720336148fd7017ffe0910f03a5c4/e2e_test/js-tests/test_viem_tx.mjs#L119). Right now that fails with
```
InvalidParamsRpcError: Invalid parameters were provided to the RPC method.
Double check you have provided the correct parameters.

URL: http://127.0.0.1:8545
Request body: {"method":"eth_gasPrice","params":["0x000000000000000000000000000000000000ce16"]}

Details: too many arguments, want at most 0
Version: viem@2.9.6
      at withRetry.delay.count.count (file:///Users/karl/op-geth-wt2/e2e_test/js-tests/node_modules/viem/_esm/utils/buildRequest.js:29:31)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async attemptRetry (file:///Users/karl/op-geth-wt2/e2e_test/js-tests/node_modules/viem/_esm/utils/promise/withRetry.js:12:30)
```

**Comment by ezdac** [comment]
Related: #68

**Comment by ezdac** [comment]
Closing this in favor of https://github.com/celo-org/op-geth/issues/68, since this is part of a meta issue - please reopen if this issue here is concerned with something different and is not redundant.
